# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(1102, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pack1 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1.setGeometry(QtCore.QRect(10, 50, 241, 141))
        self.pack1.setObjectName("pack1")
        self.rpmO = QtWidgets.QLCDNumber(self.pack1)
        self.rpmO.setGeometry(QtCore.QRect(110, 30, 64, 23))
        self.rpmO.setObjectName("rpmO")
        self.ectO = QtWidgets.QLCDNumber(self.pack1)
        self.ectO.setGeometry(QtCore.QRect(110, 70, 64, 23))
        self.ectO.setObjectName("ectO")
        self.lambdaO = QtWidgets.QLCDNumber(self.pack1)
        self.lambdaO.setGeometry(QtCore.QRect(110, 110, 64, 23))
        self.lambdaO.setObjectName("lambdaO")
        self.check1 = QtWidgets.QPushButton(self.pack1)
        self.check1.setGeometry(QtCore.QRect(200, 10, 16, 16))
        self.check1.setText("")
        self.check1.setObjectName("check1")
        self.label = QtWidgets.QLabel(self.pack1)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.pack1)
        self.label_2.setGeometry(QtCore.QRect(190, 30, 55, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.pack1)
        self.label_3.setGeometry(QtCore.QRect(190, 70, 55, 21))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.pack1)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 55, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.pack1)
        self.label_5.setGeometry(QtCore.QRect(190, 110, 55, 21))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.pack1)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 55, 21))
        self.label_6.setObjectName("label_6")
        self.pack1_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_2.setGeometry(QtCore.QRect(260, 50, 271, 191))
        self.pack1_2.setObjectName("pack1_2")
        self.fuelPressureO = QtWidgets.QLCDNumber(self.pack1_2)
        self.fuelPressureO.setGeometry(QtCore.QRect(110, 70, 64, 23))
        self.fuelPressureO.setObjectName("fuelPressureO")
        self.tpsO = QtWidgets.QLCDNumber(self.pack1_2)
        self.tpsO.setGeometry(QtCore.QRect(110, 110, 64, 23))
        self.tpsO.setObjectName("tpsO")
        self.check2 = QtWidgets.QPushButton(self.pack1_2)
        self.check2.setGeometry(QtCore.QRect(250, 10, 16, 16))
        self.check2.setText("")
        self.check2.setObjectName("check2")
        self.mapO = QtWidgets.QLCDNumber(self.pack1_2)
        self.mapO.setGeometry(QtCore.QRect(110, 30, 64, 23))
        self.mapO.setObjectName("mapO")
        self.appsO = QtWidgets.QLCDNumber(self.pack1_2)
        self.appsO.setGeometry(QtCore.QRect(110, 150, 64, 23))
        self.appsO.setObjectName("appsO")
        self.label_50 = QtWidgets.QLabel(self.pack1_2)
        self.label_50.setGeometry(QtCore.QRect(190, 30, 55, 21))
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.label_49 = QtWidgets.QLabel(self.pack1_2)
        self.label_49.setGeometry(QtCore.QRect(20, 30, 55, 21))
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.pack1_2)
        self.label_51.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.pack1_2)
        self.label_52.setGeometry(QtCore.QRect(190, 70, 55, 21))
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.label_56 = QtWidgets.QLabel(self.pack1_2)
        self.label_56.setGeometry(QtCore.QRect(190, 110, 55, 21))
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.label_55 = QtWidgets.QLabel(self.pack1_2)
        self.label_55.setGeometry(QtCore.QRect(20, 110, 55, 21))
        self.label_55.setObjectName("label_55")
        self.label_53 = QtWidgets.QLabel(self.pack1_2)
        self.label_53.setGeometry(QtCore.QRect(20, 150, 55, 21))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.pack1_2)
        self.label_54.setGeometry(QtCore.QRect(190, 150, 55, 21))
        self.label_54.setText("")
        self.label_54.setObjectName("label_54")
        self.pack1_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_3.setGeometry(QtCore.QRect(540, 50, 261, 191))
        self.pack1_3.setObjectName("pack1_3")
        self.batteryVoltageO = QtWidgets.QLCDNumber(self.pack1_3)
        self.batteryVoltageO.setGeometry(QtCore.QRect(130, 30, 64, 23))
        self.batteryVoltageO.setObjectName("batteryVoltageO")
        self.breakPreassureO = QtWidgets.QLCDNumber(self.pack1_3)
        self.breakPreassureO.setGeometry(QtCore.QRect(130, 70, 64, 23))
        self.breakPreassureO.setObjectName("breakPreassureO")
        self.airTempO = QtWidgets.QLCDNumber(self.pack1_3)
        self.airTempO.setGeometry(QtCore.QRect(130, 110, 64, 23))
        self.airTempO.setObjectName("airTempO")
        self.check3 = QtWidgets.QPushButton(self.pack1_3)
        self.check3.setGeometry(QtCore.QRect(240, 10, 16, 16))
        self.check3.setText("")
        self.check3.setObjectName("check3")
        self.oilPressureO = QtWidgets.QLCDNumber(self.pack1_3)
        self.oilPressureO.setGeometry(QtCore.QRect(130, 150, 64, 23))
        self.oilPressureO.setObjectName("oilPressureO")
        self.label_42 = QtWidgets.QLabel(self.pack1_3)
        self.label_42.setGeometry(QtCore.QRect(210, 30, 55, 21))
        self.label_42.setObjectName("label_42")
        self.label_41 = QtWidgets.QLabel(self.pack1_3)
        self.label_41.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label_41.setObjectName("label_41")
        self.label_43 = QtWidgets.QLabel(self.pack1_3)
        self.label_43.setGeometry(QtCore.QRect(20, 70, 91, 21))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.pack1_3)
        self.label_44.setGeometry(QtCore.QRect(210, 70, 55, 21))
        self.label_44.setObjectName("label_44")
        self.label_46 = QtWidgets.QLabel(self.pack1_3)
        self.label_46.setGeometry(QtCore.QRect(210, 110, 55, 21))
        self.label_46.setObjectName("label_46")
        self.label_45 = QtWidgets.QLabel(self.pack1_3)
        self.label_45.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_45.setObjectName("label_45")
        self.label_48 = QtWidgets.QLabel(self.pack1_3)
        self.label_48.setGeometry(QtCore.QRect(196, 150, 55, 21))
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_47 = QtWidgets.QLabel(self.pack1_3)
        self.label_47.setGeometry(QtCore.QRect(20, 150, 81, 21))
        self.label_47.setObjectName("label_47")
        self.pack1_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_4.setGeometry(QtCore.QRect(820, 50, 271, 191))
        self.pack1_4.setObjectName("pack1_4")
        self.velocidadActualO = QtWidgets.QLCDNumber(self.pack1_4)
        self.velocidadActualO.setGeometry(QtCore.QRect(140, 30, 64, 23))
        self.velocidadActualO.setObjectName("velocidadActualO")
        self.velocidadObjetivoO = QtWidgets.QLCDNumber(self.pack1_4)
        self.velocidadObjetivoO.setGeometry(QtCore.QRect(140, 70, 64, 23))
        self.velocidadObjetivoO.setObjectName("velocidadObjetivoO")
        self.anguloActualO = QtWidgets.QLCDNumber(self.pack1_4)
        self.anguloActualO.setGeometry(QtCore.QRect(140, 110, 64, 23))
        self.anguloActualO.setObjectName("anguloActualO")
        self.check4 = QtWidgets.QPushButton(self.pack1_4)
        self.check4.setGeometry(QtCore.QRect(250, 10, 16, 16))
        self.check4.setText("")
        self.check4.setObjectName("check4")
        self.anguloObjetivoO = QtWidgets.QLCDNumber(self.pack1_4)
        self.anguloObjetivoO.setGeometry(QtCore.QRect(140, 150, 64, 23))
        self.anguloObjetivoO.setObjectName("anguloObjetivoO")
        self.label_34 = QtWidgets.QLabel(self.pack1_4)
        self.label_34.setGeometry(QtCore.QRect(220, 30, 55, 21))
        self.label_34.setObjectName("label_34")
        self.label_33 = QtWidgets.QLabel(self.pack1_4)
        self.label_33.setGeometry(QtCore.QRect(20, 30, 101, 21))
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.pack1_4)
        self.label_35.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.pack1_4)
        self.label_36.setGeometry(QtCore.QRect(220, 70, 55, 21))
        self.label_36.setObjectName("label_36")
        self.label_38 = QtWidgets.QLabel(self.pack1_4)
        self.label_38.setGeometry(QtCore.QRect(220, 110, 55, 21))
        self.label_38.setObjectName("label_38")
        self.label_37 = QtWidgets.QLabel(self.pack1_4)
        self.label_37.setGeometry(QtCore.QRect(20, 110, 91, 21))
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.pack1_4)
        self.label_39.setGeometry(QtCore.QRect(20, 150, 101, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.pack1_4)
        self.label_40.setGeometry(QtCore.QRect(220, 150, 55, 21))
        self.label_40.setObjectName("label_40")
        self.pack1_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_5.setGeometry(QtCore.QRect(20, 320, 231, 181))
        self.pack1_5.setObjectName("pack1_5")
        self.frenoActualO = QtWidgets.QLCDNumber(self.pack1_5)
        self.frenoActualO.setGeometry(QtCore.QRect(100, 30, 64, 23))
        self.frenoActualO.setObjectName("frenoActualO")
        self.frenoObjetivoO = QtWidgets.QLCDNumber(self.pack1_5)
        self.frenoObjetivoO.setGeometry(QtCore.QRect(100, 70, 64, 23))
        self.frenoObjetivoO.setObjectName("frenoObjetivoO")
        self.motorActualO = QtWidgets.QLCDNumber(self.pack1_5)
        self.motorActualO.setGeometry(QtCore.QRect(100, 110, 64, 23))
        self.motorActualO.setObjectName("motorActualO")
        self.check5 = QtWidgets.QPushButton(self.pack1_5)
        self.check5.setGeometry(QtCore.QRect(200, 10, 16, 16))
        self.check5.setText("")
        self.check5.setObjectName("check5")
        self.motorObjetivoO = QtWidgets.QLCDNumber(self.pack1_5)
        self.motorObjetivoO.setGeometry(QtCore.QRect(100, 150, 64, 23))
        self.motorObjetivoO.setObjectName("motorObjetivoO")
        self.label_8 = QtWidgets.QLabel(self.pack1_5)
        self.label_8.setGeometry(QtCore.QRect(-60, 30, 55, 21))
        self.label_8.setObjectName("label_8")
        self.label_58 = QtWidgets.QLabel(self.pack1_5)
        self.label_58.setGeometry(QtCore.QRect(180, 30, 55, 21))
        self.label_58.setObjectName("label_58")
        self.label_57 = QtWidgets.QLabel(self.pack1_5)
        self.label_57.setGeometry(QtCore.QRect(4, 30, 81, 21))
        self.label_57.setObjectName("label_57")
        self.label_11 = QtWidgets.QLabel(self.pack1_5)
        self.label_11.setGeometry(QtCore.QRect(180, 110, 55, 21))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.pack1_5)
        self.label_12.setGeometry(QtCore.QRect(4, 110, 81, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.pack1_5)
        self.label_13.setGeometry(QtCore.QRect(180, 150, 55, 21))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.pack1_5)
        self.label_14.setGeometry(QtCore.QRect(4, 150, 91, 21))
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.pack1_5)
        self.label_10.setGeometry(QtCore.QRect(4, 70, 91, 21))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.pack1_5)
        self.label_9.setGeometry(QtCore.QRect(180, 70, 55, 21))
        self.label_9.setObjectName("label_9")
        self.pack1_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_6.setGeometry(QtCore.QRect(260, 320, 491, 191))
        self.pack1_6.setObjectName("pack1_6")
        self.asStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.asStateO.setGeometry(QtCore.QRect(130, 30, 64, 23))
        self.asStateO.setObjectName("asStateO")
        self.ebsStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.ebsStateO.setGeometry(QtCore.QRect(130, 70, 64, 23))
        self.ebsStateO.setObjectName("ebsStateO")
        self.missionSelectedO = QtWidgets.QLCDNumber(self.pack1_6)
        self.missionSelectedO.setGeometry(QtCore.QRect(130, 110, 64, 23))
        self.missionSelectedO.setObjectName("missionSelectedO")
        self.check6 = QtWidgets.QPushButton(self.pack1_6)
        self.check6.setGeometry(QtCore.QRect(470, 10, 16, 16))
        self.check6.setText("")
        self.check6.setObjectName("check6")
        self.steeringStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.steeringStateO.setGeometry(QtCore.QRect(130, 150, 64, 23))
        self.steeringStateO.setObjectName("steeringStateO")
        self.breakStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.breakStateO.setGeometry(QtCore.QRect(360, 30, 64, 23))
        self.breakStateO.setObjectName("breakStateO")
        self.lapCounterO = QtWidgets.QLCDNumber(self.pack1_6)
        self.lapCounterO.setGeometry(QtCore.QRect(360, 70, 64, 23))
        self.lapCounterO.setObjectName("lapCounterO")
        self.conosActualesO = QtWidgets.QLCDNumber(self.pack1_6)
        self.conosActualesO.setGeometry(QtCore.QRect(360, 110, 64, 23))
        self.conosActualesO.setObjectName("conosActualesO")
        self.label_16 = QtWidgets.QLabel(self.pack1_6)
        self.label_16.setGeometry(QtCore.QRect(210, 30, 55, 21))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.pack1_6)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.pack1_6)
        self.label_17.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.pack1_6)
        self.label_18.setGeometry(QtCore.QRect(210, 70, 55, 21))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.pack1_6)
        self.label_20.setGeometry(QtCore.QRect(210, 110, 55, 21))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.pack1_6)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 101, 21))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.pack1_6)
        self.label_22.setGeometry(QtCore.QRect(210, 150, 55, 21))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.pack1_6)
        self.label_21.setGeometry(QtCore.QRect(20, 150, 91, 21))
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.pack1_6)
        self.label_24.setGeometry(QtCore.QRect(440, 30, 55, 21))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.pack1_6)
        self.label_23.setGeometry(QtCore.QRect(264, 30, 61, 21))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.pack1_6)
        self.label_25.setGeometry(QtCore.QRect(264, 70, 81, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.pack1_6)
        self.label_26.setGeometry(QtCore.QRect(440, 70, 55, 21))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.pack1_6)
        self.label_27.setGeometry(QtCore.QRect(264, 110, 91, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.pack1_6)
        self.label_28.setGeometry(QtCore.QRect(440, 110, 55, 21))
        self.label_28.setObjectName("label_28")
        self.pack1_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_7.setGeometry(QtCore.QRect(770, 320, 241, 141))
        self.pack1_7.setObjectName("pack1_7")
        self.asmsO = QtWidgets.QLCDNumber(self.pack1_7)
        self.asmsO.setGeometry(QtCore.QRect(90, 30, 64, 23))
        self.asmsO.setObjectName("asmsO")
        self.goSignalO = QtWidgets.QLCDNumber(self.pack1_7)
        self.goSignalO.setGeometry(QtCore.QRect(90, 70, 64, 23))
        self.goSignalO.setObjectName("goSignalO")
        self.check7 = QtWidgets.QPushButton(self.pack1_7)
        self.check7.setGeometry(QtCore.QRect(220, 10, 16, 16))
        self.check7.setText("")
        self.check7.setObjectName("check7")
        self.label_30 = QtWidgets.QLabel(self.pack1_7)
        self.label_30.setGeometry(QtCore.QRect(170, 30, 55, 21))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_29 = QtWidgets.QLabel(self.pack1_7)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 55, 21))
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.pack1_7)
        self.label_32.setGeometry(QtCore.QRect(170, 70, 55, 21))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_31 = QtWidgets.QLabel(self.pack1_7)
        self.label_31.setGeometry(QtCore.QRect(20, 70, 55, 21))
        self.label_31.setObjectName("label_31")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pack1.setTitle(_translate("MainWindow", "Paquete 1"))
        self.label.setText(_translate("MainWindow", "Revoluciones:"))
        self.label_2.setText(_translate("MainWindow", "rpm"))
        self.label_4.setText(_translate("MainWindow", "Ect:"))
        self.label_6.setText(_translate("MainWindow", "Lambda:"))
        self.pack1_2.setTitle(_translate("MainWindow", "Paquete 2"))
        self.label_49.setText(_translate("MainWindow", "Map"))
        self.label_51.setText(_translate("MainWindow", "FuelPressure:"))
        self.label_55.setText(_translate("MainWindow", "TPS:"))
        self.label_53.setText(_translate("MainWindow", "APPS:"))
        self.pack1_3.setTitle(_translate("MainWindow", "Paquete 3"))
        self.label_42.setText(_translate("MainWindow", "V"))
        self.label_41.setText(_translate("MainWindow", "BatteryVoltage"))
        self.label_43.setText(_translate("MainWindow", "BreakPreassure"))
        self.label_44.setText(_translate("MainWindow", "%"))
        self.label_46.setText(_translate("MainWindow", "ºC"))
        self.label_45.setText(_translate("MainWindow", "AirTemp"))
        self.label_47.setText(_translate("MainWindow", "OilPressure"))
        self.pack1_4.setTitle(_translate("MainWindow", "Paquete 4"))
        self.label_34.setText(_translate("MainWindow", "km/h"))
        self.label_33.setText(_translate("MainWindow", "VelocidadActual"))
        self.label_35.setText(_translate("MainWindow", "VelocidadObjetivo"))
        self.label_36.setText(_translate("MainWindow", "km/h"))
        self.label_38.setText(_translate("MainWindow", "º"))
        self.label_37.setText(_translate("MainWindow", "AnguloActual"))
        self.label_39.setText(_translate("MainWindow", "AnguloObjetivo"))
        self.label_40.setText(_translate("MainWindow", "º"))
        self.pack1_5.setTitle(_translate("MainWindow", "Paquete 5"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_58.setText(_translate("MainWindow", "%"))
        self.label_57.setText(_translate("MainWindow", "FrenoActual"))
        self.label_12.setText(_translate("MainWindow", "MotorActual"))
        self.label_14.setText(_translate("MainWindow", "MotorObjetivo"))
        self.label_10.setText(_translate("MainWindow", "FrenoObjetivo"))
        self.label_9.setText(_translate("MainWindow", "%"))
        self.pack1_6.setTitle(_translate("MainWindow", "Paquete 6"))
        self.label_15.setText(_translate("MainWindow", "ASState"))
        self.label_17.setText(_translate("MainWindow", "EBSState"))
        self.label_19.setText(_translate("MainWindow", "MissionSelected"))
        self.label_21.setText(_translate("MainWindow", "SteeringState"))
        self.label_23.setText(_translate("MainWindow", "BreakState"))
        self.label_25.setText(_translate("MainWindow", "LapCounter"))
        self.label_27.setText(_translate("MainWindow", "ConosActuales"))
        self.label_28.setText(_translate("MainWindow", "nº"))
        self.pack1_7.setTitle(_translate("MainWindow", "Paquete 7"))
        self.label_29.setText(_translate("MainWindow", "Asms"))
        self.label_31.setText(_translate("MainWindow", "GoSignal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

