# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(1033, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pack1 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1.setGeometry(QtCore.QRect(40, 30, 141, 141))
        self.pack1.setObjectName("pack1")
        self.rpmO = QtWidgets.QLCDNumber(self.pack1)
        self.rpmO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.rpmO.setObjectName("rpmO")
        self.ectO = QtWidgets.QLCDNumber(self.pack1)
        self.ectO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.ectO.setObjectName("ectO")
        self.lambdaO = QtWidgets.QLCDNumber(self.pack1)
        self.lambdaO.setGeometry(QtCore.QRect(10, 110, 64, 23))
        self.lambdaO.setObjectName("lambdaO")
        self.pushButton = QtWidgets.QPushButton(self.pack1)
        self.pushButton.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pack1_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_2.setGeometry(QtCore.QRect(40, 190, 141, 191))
        self.pack1_2.setObjectName("pack1_2")
        self.fuelPressureO = QtWidgets.QLCDNumber(self.pack1_2)
        self.fuelPressureO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.fuelPressureO.setObjectName("fuelPressureO")
        self.tpsO = QtWidgets.QLCDNumber(self.pack1_2)
        self.tpsO.setGeometry(QtCore.QRect(10, 110, 64, 23))
        self.tpsO.setObjectName("tpsO")
        self.pushButton_2 = QtWidgets.QPushButton(self.pack1_2)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.mapO = QtWidgets.QLCDNumber(self.pack1_2)
        self.mapO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.mapO.setObjectName("mapO")
        self.appsO = QtWidgets.QLCDNumber(self.pack1_2)
        self.appsO.setGeometry(QtCore.QRect(10, 150, 64, 23))
        self.appsO.setObjectName("appsO")
        self.pack1_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_3.setGeometry(QtCore.QRect(40, 410, 141, 201))
        self.pack1_3.setObjectName("pack1_3")
        self.batteryVoltageO = QtWidgets.QLCDNumber(self.pack1_3)
        self.batteryVoltageO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.batteryVoltageO.setObjectName("batteryVoltageO")
        self.breakPreassureO = QtWidgets.QLCDNumber(self.pack1_3)
        self.breakPreassureO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.breakPreassureO.setObjectName("breakPreassureO")
        self.airrTempoO = QtWidgets.QLCDNumber(self.pack1_3)
        self.airrTempoO.setGeometry(QtCore.QRect(10, 110, 64, 23))
        self.airrTempoO.setObjectName("airrTempoO")
        self.pushButton_3 = QtWidgets.QPushButton(self.pack1_3)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.oilPressureO = QtWidgets.QLCDNumber(self.pack1_3)
        self.oilPressureO.setGeometry(QtCore.QRect(10, 150, 64, 23))
        self.oilPressureO.setObjectName("oilPressureO")
        self.pack1_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_4.setGeometry(QtCore.QRect(310, 30, 141, 181))
        self.pack1_4.setObjectName("pack1_4")
        self.velocidadActualO = QtWidgets.QLCDNumber(self.pack1_4)
        self.velocidadActualO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.velocidadActualO.setObjectName("velocidadActualO")
        self.velocidadObjetivoO = QtWidgets.QLCDNumber(self.pack1_4)
        self.velocidadObjetivoO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.velocidadObjetivoO.setObjectName("velocidadObjetivoO")
        self.anguloActualO = QtWidgets.QLCDNumber(self.pack1_4)
        self.anguloActualO.setGeometry(QtCore.QRect(10, 110, 64, 23))
        self.anguloActualO.setObjectName("anguloActualO")
        self.pushButton_4 = QtWidgets.QPushButton(self.pack1_4)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.AnguloObjetivoO = QtWidgets.QLCDNumber(self.pack1_4)
        self.AnguloObjetivoO.setGeometry(QtCore.QRect(10, 150, 64, 23))
        self.AnguloObjetivoO.setObjectName("AnguloObjetivoO")
        self.pack1_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_5.setGeometry(QtCore.QRect(310, 230, 141, 181))
        self.pack1_5.setObjectName("pack1_5")
        self.frenoActualO = QtWidgets.QLCDNumber(self.pack1_5)
        self.frenoActualO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.frenoActualO.setObjectName("frenoActualO")
        self.frenoObjetivoO = QtWidgets.QLCDNumber(self.pack1_5)
        self.frenoObjetivoO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.frenoObjetivoO.setObjectName("frenoObjetivoO")
        self.motorActualO = QtWidgets.QLCDNumber(self.pack1_5)
        self.motorActualO.setGeometry(QtCore.QRect(10, 110, 64, 23))
        self.motorActualO.setObjectName("motorActualO")
        self.pushButton_5 = QtWidgets.QPushButton(self.pack1_5)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.motorObjetivoO = QtWidgets.QLCDNumber(self.pack1_5)
        self.motorObjetivoO.setGeometry(QtCore.QRect(10, 150, 64, 23))
        self.motorObjetivoO.setObjectName("motorObjetivoO")
        self.pack1_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_6.setGeometry(QtCore.QRect(310, 430, 211, 201))
        self.pack1_6.setObjectName("pack1_6")
        self.asStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.asStateO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.asStateO.setObjectName("asStateO")
        self.ebsStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.ebsStateO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.ebsStateO.setObjectName("ebsStateO")
        self.missionSelectedO = QtWidgets.QLCDNumber(self.pack1_6)
        self.missionSelectedO.setGeometry(QtCore.QRect(10, 110, 64, 23))
        self.missionSelectedO.setObjectName("missionSelectedO")
        self.pushButton_6 = QtWidgets.QPushButton(self.pack1_6)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 10, 16, 16))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.steeringStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.steeringStateO.setGeometry(QtCore.QRect(10, 150, 64, 23))
        self.steeringStateO.setObjectName("steeringStateO")
        self.breakStateO = QtWidgets.QLCDNumber(self.pack1_6)
        self.breakStateO.setGeometry(QtCore.QRect(110, 30, 64, 23))
        self.breakStateO.setObjectName("breakStateO")
        self.lapCounterO = QtWidgets.QLCDNumber(self.pack1_6)
        self.lapCounterO.setGeometry(QtCore.QRect(110, 70, 64, 23))
        self.lapCounterO.setObjectName("lapCounterO")
        self.conosActualesO = QtWidgets.QLCDNumber(self.pack1_6)
        self.conosActualesO.setGeometry(QtCore.QRect(110, 110, 64, 23))
        self.conosActualesO.setObjectName("conosActualesO")
        self.pack1_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.pack1_7.setGeometry(QtCore.QRect(560, 30, 141, 141))
        self.pack1_7.setObjectName("pack1_7")
        self.asmsO = QtWidgets.QLCDNumber(self.pack1_7)
        self.asmsO.setGeometry(QtCore.QRect(10, 30, 64, 23))
        self.asmsO.setObjectName("asmsO")
        self.goSignalO = QtWidgets.QLCDNumber(self.pack1_7)
        self.goSignalO.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.goSignalO.setObjectName("goSignalO")
        self.pushButton_7 = QtWidgets.QPushButton(self.pack1_7)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pack1.setTitle(_translate("MainWindow", "Paquete 1"))
        self.pack1_2.setTitle(_translate("MainWindow", "Paquete 2"))
        self.pack1_3.setTitle(_translate("MainWindow", "Paquete 3"))
        self.pack1_4.setTitle(_translate("MainWindow", "Paquete 4"))
        self.pack1_5.setTitle(_translate("MainWindow", "Paquete 5"))
        self.pack1_6.setTitle(_translate("MainWindow", "Paquete 6"))
        self.pack1_7.setTitle(_translate("MainWindow", "Paquete 7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

